---

- name: mongodb reload
  service: name=mongod state=reloaded
  when: mongodb_manage_service

- name: mongodb restart
  service: name=mongod state=restarted
  when: mongodb_manage_service

- name: mongodb-mms-automation-agent restart
  service: name=mongodb-mms-automation-agent state=restarted
  when: mongodb_manage_service
